### ISSUE TITLE
Missing project.pbxproj file.

### ISSUE THREAD

**Issue by sistla234** [paul-ferragut/iOSoscTouchObject#1]
Hi Paul,

I am trying to use your code to understand touchObjects with OF. I'm new to using OF and when I try opening the .xcodeproj file in your project it give me the following error:

/Downloads/iOSoscTouchObject-master/iOSoscTouchObject.xcodeproj cannot be opened because it is missing its project.pbxproj file.

Is there something that I am doing wrong with the download?

**Comment by paul-ferragut** [comment]
Hi!
I might have forgotten this file however I dont have my mac with me to upload it at the moment
I would recommend downloading the last version of openframeworks with iOS and testing first if the openframeworks examples are working. then creating a new project and copying/replacing with the file from iOSoscTouchObject (to create a new project you can copy an of example or to use the project generator to create a new app)

**Comment by sistla234** [comment]
Thank you for the response. I'll try your suggested route and please update me when you do upload the project.pbxproj file on the repo
