### ISSUE TITLE
project.pbxproj is missing

### ISSUE THREAD

**Issue by HopperCat** [paul-ferragut/iOSoscTouchObject#2]
Hi Paul,
Im trying to open this project in Xcode but I get this error:

Project ../iOSoscTouchObject-master/iOSoscTouchObject.xcodeproj cannot be opened because it is missing its project.pbxproj file

**Comment by HopperCat** [comment]
I just saw the other closed issue. Followed your advice and could run it without a problem. Thanks!

**Comment by paul-ferragut** [comment]
I am glad you managed, sorry not helping with this one I dont have a mac with me atm.
If you can you fork and upload the project.pbxproj file to the repo it would be great

**Comment by paul-ferragut** [comment]
merged your project file. Thank you for your contribution!

**Comment by HopperCat** [comment]
Glad I can contribute!
